version: '3'
services:
  rabbit:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  rabbit_mq_bot:
    container_name: rabbit_mq_bot
    links:
      - rabbit
    build:
      context: .
      dockerfile: Dockerfile
    image: rabbit_mq_bot:latest
    ports:
      - "8085:8085"
    environment:
      RABBIT_HOST: rabbit
    volumes:
      - ./audio:/audio
    depends_on:
      - rabbit

